version: '3.3'

# Establecemos una red personalizada.
networks:
  isolation-network:
    name: isolation-network
    driver: bridge

services:
  chatbot:
    # Imágen a utilizar:
    image: tensorflow/serving:2.6.0
    container_name: chatbot_tfx
    # Utilizamos la red personalizada:
    networks: 
      - isolation-network
    # Le asignamos un "hostname" para realizar las peticiones:
    hostname: chatbot
    ports:
      # Enlazamos el puerto en el que trabaja el BOT
      - "8501:8501"
    expose: 
      - "8501"
    volumes:
      - type: bind
        source: ./chatbot
        target: /models/chatbot
    environment:
      - MODEL_NAME=chatbot
     